// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  SCREENSHOT_SERVICE_API_KEY: string;
  SCREENSHOT_SERVICE_ORIGIN: string;
  WAYBACK_API_TOKEN: string;
  OPENAI_API_KEY: string;
  RESEND_API_KEY: string;
  FROM_EMAIL: string;
  archive: R2Bucket;
  DIFF_DB: D1Database;
  COMPETITOR_DB: D1Database;
}
